# Generated by Django 5.1.2 on 2024-10-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_tags_post_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/post_default.png', null=True, upload_to='media'),
        ),
    ]
